피마 인디언 당뇨병 예측 (diabetes)모델의 성능을 평가하세요.

- LogisticRegression
- f1 score,Confusion Matrix
- 전처리후 성능 모델의 성능을 향상 시켜 보세요.
- f1 score, Confusion Matrix 확인요.

=========================================================

북아메리카 피마 지역 원주민의 Type-2 당뇨병 결과 데이터

Pregnancies: 임신 횟수
Glucose: 포도당 부하 검사 수치
BloodPressure: 혈압(mm Hg)
SkinThickness: 팔 삼두근 뒤쪽의 피하지방 측정값(mm)
Insulin: 혈청 인슐린(mu U/ml)
BMI: 체질량지수(체중(kg)/(키(m))^2)
DiabetesPedigreeFunction: 당뇨 내력 가중치 값
Age: 나이
Outcome: 클래스 결정 값(0또는 1)

In [1]:
import warnings
warnings.filterwarnings('ignore') # 경고메세지 무시 코드

from preamble import *
plt.rcParams['image.cmap'] = "gray"
from IPython.display import display
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import mglearn
import pandas as pd
import numpy as np
from preamble import *

import platform
import matplotlib.pyplot as plt
%matplotlib inline

path = "c:/Windows/Fonts/malgun.ttf"
from matplotlib import font_manager, rc
if platform.system() == 'Darwin':
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system... sorry~~~~')    

plt.rcParams['axes.unicode_minus'] = False

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [56]:
dia=pd.read_csv("../../data/diabetes.csv")

Pregnancies  Glucose  BloodPressure  SkinThickness  ...   BMI  \
0              6      148             72             35  ...  33.6   
1              1       85             66             29  ...  26.6   
2              8      183             64              0  ...  23.3   
3              1       89             66             23  ...  28.1   
4              0      137             40             35  ...  43.1   
..           ...      ...            ...            ...  ...   ...   
763           10      101             76             48  ...  32.9   
764            2      122             70             27  ...  36.8   
765            5      121             72             23  ...  26.2   
766            1      126             60              0  ...  30.1   
767            1       93             70             31  ...  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                        0.63   50        1  
1                        0.35   31        0  
2                        0.67   32        1  
3                        0.17   21        0  
4                        2.29   33        1  
..                        ...  ...      ...  
763                      0.17   63        0  
764                      0.34   27        0  
765                      0.24   30        0  
766                      0.35   47        1  
767                      0.32   23        0  

[768 rows x 9 columns]

In [4]:
X=dia.iloc[:,:-1]
y=dia.iloc[:,-1]
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                      0.63   50  
1                      0.35   31  
2                      0.67   32  
3                      0.17   21  
4                      2.29   33

In [5]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=0)
X_train.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
762            9       89             62              0        0  22.5   
127            1      118             58             36       94  33.3   
564            0       91             80              0        0  32.4   
375           12      140             82             43      325  39.2   
663            9      145             80             46      130  37.9   

     DiabetesPedigreeFunction  Age  
762                      0.14   33  
127                      0.26   23  
564                      0.60   27  
375                      0.53   58  
663                      0.64   40

In [7]:
y_train.head()

762    0
127    0
564    0
375    1
663    1
Name: Outcome, dtype: int64

In [8]:
logreg = LogisticRegression().fit(X_train, y_train)
print("테스트 세트 점수: {:.2f}".format(logreg.score(X_test, y_test)))

테스트 세트 점수: 0.79


In [14]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(C=0.1).fit(X_train, y_train)
pred_logreg = logreg.predict(X_test)
print("logreg 점수: {:.2f}".format(logreg.score(X_test, y_test)))

logreg 점수: 0.80


In [15]:
from sklearn.metrics import confusion_matrix

confusion = confusion_matrix(y_test, pred_logreg)
print("오차 행렬:\n", confusion)

오차 행렬:
 [[117  13]
 [ 26  36]]


In [18]:
from sklearn.metrics import f1_score
print("logreg 점수: {:.2f}".format(f1_score(y_test,pred_logreg)))

logreg 점수: 0.65


# 검증(Cross Validation)

In [19]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(logreg, 
                         X, 
                         y)
print("교차 검증 점수:", scores)

교차 검증 점수: [0.753 0.74  0.766 0.81  0.752]


In [20]:
scores = cross_val_score(logreg, 
                         X, 
                         y, 
                         cv=5)
print("교차 검증 점수:", scores)
print("교차 검증 평균 점수: {:.2f}".format(scores.mean()))

교차 검증 점수: [0.753 0.74  0.766 0.81  0.752]
교차 검증 평균 점수: 0.76


In [21]:
from sklearn.model_selection import cross_validate
res = cross_validate(logreg, 
                     X, 
                     y, 
                     cv=5,
                     return_train_score=True)
display(res)

{'fit_time': array([0.023, 0.024, 0.018, 0.018, 0.018]),
 'score_time': array([0.002, 0.001, 0.002, 0.001, 0.001]),
 'test_score': array([0.753, 0.74 , 0.766, 0.81 , 0.752]),
 'train_score': array([0.775, 0.779, 0.774, 0.771, 0.776])}

In [22]:
from sklearn.model_selection import KFold
kfold = KFold(n_splits=5)

In [23]:
print("교차 검증 점수:\n",cross_val_score(logreg, 
                                          X, 
                                          y, 
                                          cv=kfold))

교차 검증 점수:
 [0.753 0.708 0.766 0.85  0.765]


In [24]:
kfold = KFold(n_splits=3)
print("교차 검증 점수:\n",cross_val_score(logreg, 
                                          X, 
                                          y, 
                                          cv=kfold))

교차 검증 점수:
 [0.758 0.758 0.793]


In [25]:
kfold = KFold(n_splits=3, shuffle=True, random_state=0)
print("교차 검증 점수:\n",cross_val_score(logreg, 
                                          X, 
                                          y, 
                                          cv=kfold))

교차 검증 점수:
 [0.785 0.77  0.746]


In [27]:
from sklearn.model_selection import LeaveOneOut
loo = LeaveOneOut()
scores = cross_val_score(logreg, 
                         X, 
                         y, 
                         cv=kfold)

print('iris.data.shape \n{}'.format(dia.shape))
print("교차 검증 분할 횟수: ", len(scores))
print("평균 정확도: {:.2f}".format(scores.mean()))

iris.data.shape 
(768, 9)
교차 검증 분할 횟수:  3
평균 정확도: 0.77


# 임의 분할 교차 검증

In [28]:
from sklearn.model_selection import ShuffleSplit
shuffle_split = ShuffleSplit(test_size=.5, 
                             train_size=.5, 
                             n_splits=10)

scores = cross_val_score(logreg, 
                         X, 
                         y, 
                         cv=shuffle_split)

print("교차 검증 점수:\n", scores)
print("평균 정확도: {:.2f}".format(scores.mean()))

교차 검증 점수:
 [0.781 0.755 0.76  0.771 0.773 0.732 0.75  0.75  0.742 0.753]
평균 정확도: 0.76


# 자료 정제
### Insulin 수치가 0인 것은 drop!

In [58]:
dia2=dia.drop(dia[dia['Insulin']==0]['Insulin'].index)
dia2

Pregnancies  Glucose  BloodPressure  SkinThickness  ...   BMI  \
3              1       89             66             23  ...  28.1   
4              0      137             40             35  ...  43.1   
6              3       78             50             32  ...  31.0   
8              2      197             70             45  ...  30.5   
13             1      189             60             23  ...  30.1   
..           ...      ...            ...            ...  ...   ...   
753            0      181             88             44  ...  43.3   
755            1      128             88             39  ...  36.5   
760            2       88             58             26  ...  28.4   
763           10      101             76             48  ...  32.9   
765            5      121             72             23  ...  26.2   

     DiabetesPedigreeFunction  Age  Outcome  
3                        0.17   21        0  
4                        2.29   33        1  
6                        0.25   26        1  
8                        0.16   53        1  
13                       0.40   59        1  
..                        ...  ...      ...  
753                      0.22   26        1  
755                      1.06   37        1  
760                      0.77   22        0  
763                      0.17   63        0  
765                      0.24   30        0  

[394 rows x 9 columns]

In [59]:
dia2['Insulin']

3       94
4      168
6       88
8      543
13     846
      ... 
753    510
755    110
760     16
763    180
765    112
Name: Insulin, Length: 394, dtype: int64

In [60]:
X=dia2.iloc[:,:-1]
y=dia2.iloc[:,-1]
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
3             1       89             66             23       94  28.1   
4             0      137             40             35      168  43.1   
6             3       78             50             32       88  31.0   
8             2      197             70             45      543  30.5   
13            1      189             60             23      846  30.1   

    DiabetesPedigreeFunction  Age  
3                       0.17   21  
4                       2.29   33  
6                       0.25   26  
8                       0.16   53  
13                      0.40   59

In [61]:
y.head()

3     0
4     1
6     1
8     1
13    1
Name: Outcome, dtype: int64

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=0)
X_train.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
425            4      184             78             39      277  37.0   
478            8      126             74             38       75  25.9   
186            8      181             68             36      495  30.1   
340            1      130             70             13      105  25.9   
51             1      101             50             15       36  24.2   

     DiabetesPedigreeFunction  Age  
425                      0.26   31  
478                      0.16   39  
186                      0.61   60  
340                      0.47   22  
51                       0.53   26

In [63]:
logreg = LogisticRegression().fit(X_train, y_train)
print("테스트 세트 점수: {:.2f}".format(logreg.score(X_test, y_test)))

테스트 세트 점수: 0.85


In [66]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(C=0.1).fit(X_train, y_train)
pred_logreg = logreg.predict(X_test)
print("logreg 점수: {:.2f}".format(logreg.score(X_test, y_test)))

logreg 점수: 0.82


In [67]:
from sklearn.metrics import confusion_matrix

confusion = confusion_matrix(y_test, pred_logreg)
print("오차 행렬:\n", confusion)

오차 행렬:
 [[64  3]
 [15 17]]


In [68]:
from sklearn.metrics import f1_score
print("logreg 점수: {:.2f}".format(f1_score(y_test,pred_logreg)))

logreg 점수: 0.65


In [69]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(logreg, 
                         X, 
                         y)
print("교차 검증 점수:", scores)

교차 검증 점수: [0.785 0.709 0.747 0.785 0.833]


In [70]:
scores = cross_val_score(logreg, 
                         X, 
                         y, 
                         cv=5)
print("교차 검증 점수:", scores)
print("교차 검증 평균 점수: {:.2f}".format(scores.mean()))

교차 검증 점수: [0.785 0.709 0.747 0.785 0.833]
교차 검증 평균 점수: 0.77
