In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.15.0


# 1. Dimensional Tensor - Vector

In [3]:
import numpy as np
tensor_1d = np.array([1.3, 1, 4.0, 23.99])
tensor_1d
print(f'{tensor_1d[0]},\n{tensor_1d[1]},\n{tensor_1d[2]},\n{tensor_1d[3]}')

1.3,
1.0,
4.0,
23.99


# 2. Dimensional Tensor - Matrix

In [4]:
tensor_2d = np.array([(1, 2, 3, 4), 
                      (4, 5, 6, 7), 
                      (8, 9,10, 11), 
                      (12, 13, 14, 15)])
print(f'{tensor_2d},\n\n{tensor_2d[3][2]}')

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]],

14


# Data Flow Graph

### Session

In [5]:
a = tf.add(3, 5)
sess = tf.Session()
print(sess.run(a))
sess.close()

8


# Operators

In [6]:
x = 2
y = 3
op1 = tf.add(x, y)
op2 = tf.multiply(x, y)
op3 = tf.pow(op2, op1)
with tf.Session() as sess:
 op3 = sess.run(op3)

# TensorBoard
### ▪A visualization software that comes with any standard TensorFlow installation
### 텐서플로우 설치하면 같이 오는 시각화소프트웨어

# Visualizing Graph

In [7]:
import tensorflow as tf
tf.reset_default_graph()
x = 2
y = 3
op1 = tf.add(x, y)
op2 = tf.multiply(x, y)
op3 = tf.pow(op2, op1)

with tf.Session() as sess:
 tf.summary.FileWriter('./graphs',sess.graph)
 op3 = sess.run(op3)
 writer = tf.summary.FileWriter('./graphs',sess.graph)

In [8]:
# Exercise #3
a = 2
b = 3
c = tf.add(a,b,name='Add')
print(c)

Tensor("Add_1:0", shape=(), dtype=int32)


In [9]:
sess = tf.Session()
print(sess.run(c))
sess.close()

5


In [10]:
with tf.Session() as sess:
 tf.summary.FileWriter('./graphs',sess.graph)
 c = sess.run(c)
 writer = tf.summary.FileWriter('./graphs',sess.graph)    

In [11]:
x = 2
y = 3
add_op = tf.add(x, y, name='Add')
mul_op = tf.multiply(x, y, name = 'Multiply')
pow_op = tf.pow(add_op, mul_op, name='Power')
useless_op = tf.multiply(x, add_op, name='Useless')

with tf.Session() as sess:
    pow_out, useless_out = sess.run([pow_op, useless_op])

# Constant
### Visualizing Graph

In [12]:
tf.reset_default_graph()
a=tf.constant(2, name="a")
b=tf.constant(3, name='b')
c=tf.add(a,b,name='addition')

with tf.Session() as sess:
    writer=tf.summary.FileWriter('./graphs', sess.graph)
    print(sess.run(c))

5


# Scalar and Matrix Constant
### 정수, 소수등으로 정의할수도 있고,
### 벡터, 메트릭스등의 모양으로 정의할수도 있음

In [13]:
s = tf.constant(2.3, name='scalar', dtype=tf.float32)

m=tf.constant([[1,2],[3,4]], name='matrix')

with tf.Session() as sess:
    print(sess.run(s))
    print(sess.run(m))

2.3
[[1 2]
 [3 4]]


In [14]:
import tensorflow as tf
import numpy as np

In [15]:
tf.reset_default_graph()
matrix_1 = np.array([(2,2,2),
                     (2,2,2),
                     (2,2,2)], dtype='int32')

matrix_2 = np.array([(1,1,1),
                     (1,1,1),
                     (1,1,1)], dtype='int32')
matrix_1 = tf.constant(matrix_1)
matrix_2 = tf.constant(matrix_2)
# 행렬곱
matrix_product = tf.matmul(matrix_1, matrix_2) 
# 행렬합
matrix_sum = tf.add(matrix_1, matrix_2)

matrix_3 = np.array([(2,7,2),
                     (1,4,2),
                     (9,0,2)], dtype = 'float32')
# 행렬 판별식
matrix_det = tf.matrix_determinant(matrix_3)

with tf.Session() as sess:
    writer=tf.summary.FileWriter('./graphs', sess.graph)
    result_1 = sess.run(matrix_product)
    result_2 = sess.run(matrix_sum)
    result_3 = sess.run(matrix_det)
print(result_1)    
print(result_2)
print(result_3)

[[6 6 6]
 [6 6 6]
 [6 6 6]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]
55.999992


# Variables
### 메모리 버퍼에 텐서를 저장
### 초기화 시켜서 사용

In [16]:
s = tf.Variable(2, name='scalar')

m = tf.Variable([1, 2],
                [3, 4], name = 'matrix')

w = tf.Variable(tf.zeros([784, 10]))

# Initialize Variables
### 우선 변수를 초기화시켜서 평가함

In [17]:
a = tf.get_variable(name="A", initializer = tf.constant(2))
b = tf.get_variable(name="B", initializer = tf.constant(3))

c = tf.add(a,b, name='Add')

# add an Op to initialize global variables
init_op = tf.global_variables_initializer()

# launch the graph in a session
with tf.Session() as sess:
    # run the variable initializer operation
    sess.run(init_op)
    # now let's evaluate their value
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))

2
3
5


# Exercise #3
### 정규분포로부터 2x3 매트릭스를 만들고, 0이 3개있는 벡터를 만들어 프린트하시요.
#### ▪Weights are usually initialized from a normal distribution using tf.truncated_normal_initializer(stddev=0.01).
#### ▪Biases are usually initialized from zeros using tf.zeros_initializer(). 

In [18]:
weight = tf.get_variable(name="w",
                         shape=[2,3] ,
                         initializer = tf.truncated_normal_initializer(stddev=0.01)) 
bias = tf.get_variable(name="b",
                       shape=[3],
                       initializer = tf.zeros_initializer())
# 초기화
init_op = tf.global_variables_initializer()

with tf.Session() as sess:
    # 초기화
    sess.run(init_op)
    print(f'{sess.run(weight)},\n\n{sess.run(bias)}')

[[ 0.00016902  0.01283116  0.01269692]
 [-0.01058214 -0.00503714  0.00089915]],

[0. 0. 0.]


# Placeholder <- 일종의 자리 예약
## 나중에 데이터를 할당
#### A variable that we assign data in a future time

In [19]:
a = tf.placeholder(tf.float32, shape=[5])
b = tf.placeholder(dtype=tf.float32, shape = None, name = None)

X = tf.placeholder(tf.float32, shape=[None, 784], name='input')
Y = tf.placeholder(tf.float32, shape=[None, 10], name='label')

# Placeholder Example

In [20]:
a = tf.constant([5,5,5], tf.float32, name = 'A')
b = tf.placeholder(tf.float32, shape=[3], name = 'B')

# 상수벡터와 플레이스홀더를 더함
c = tf.add(a, b, name = 'Add')

with tf.Session() as sess:
    # create a dictionary:
    d = {b:[1,2,3]} # 플레이스홀더 값을 만듦.
    # feed it to the placeholder
    print(sess.run(c, feed_dict=d))
    # 플레이스홀더 값을 이용하여 결과 출력    

[6. 7. 8.]


In [21]:
import numpy as np
import tensorflow as tf

with tf.variable_scope('regression', reuse=tf.AUTO_REUSE):
    X = tf.placeholder(dtype=tf.float32, 
                       shape=[100, 784], 
                       name='X')

    W = tf.get_variable(name="W",
                        shape=[784, 200],
                        initializer = tf.truncated_normal_initializer(mean=0,
                                                                      stddev=0.01),
                        dtype=tf.float32)

    B = tf.get_variable(name="B",
                        shape=[200],
                        initializer = tf.zeros_initializer(),
                        dtype=tf.float32)

    matrix_product = tf.matmul(X, W, name='multiply') 
    matrix_add = tf.add(matrix_product, B, name='add')
    ReLU = tf.nn.relu(matrix_add, name='relu')

    init_op = tf.global_variables_initializer()

In [22]:
with tf.Session() as sess:
    sess.run(init_op)
    X_dict = {X:np.random.rand(100,784)}
    sess.run(matrix_product, feed_dict=X_dict)
    sess.run(matrix_add, feed_dict=X_dict)
    print(f'{sess.run(ReLU,feed_dict=X_dict)}')
    writer=tf.summary.FileWriter('./graphs', sess.graph)

[[-0.         -0.          0.11686739 ...  0.06533074 -0.
   0.09585962]
 [-0.         -0.          0.17530107 ...  0.03638653 -0.
   0.14942399]
 [-0.         -0.          0.22464027 ...  0.08509884 -0.
   0.08214143]
 ...
 [-0.         -0.          0.3585947  ...  0.18610087 -0.
  -0.        ]
 [-0.         -0.          0.08170207 ...  0.01322826 -0.
   0.06799339]
 [-0.         -0.          0.25144726 ...  0.12781247 -0.
   0.05823798]]
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
Cannot set tensorflow.VariableDef.trainable to [3, 4]: [3, 4] has type <class 'list'>, but expected one of: (<class 'bool'>, <class 'numbers.Integral'>)
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
Cannot set tensorflow.VariableDef.trainable to [3, 4]: [3, 4] has type <class 'list'>, but expected one of: (<class 'bool'>

## sigmoid 함수

In [23]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [24]:
sigmoid(1)

0.7310585786300049

In [25]:
sigmoid(4)

0.9820137900379085

In [26]:
sigmoid(-3)

0.04742587317756678

# tanh 함수

In [27]:
def tanh(x):
    return np.tanh(x)

In [28]:
tanh(1)

0.7615941559557649

In [29]:
tanh(-1)

-0.7615941559557649

# Components of Neural Networks
## Neural Network Model

In [30]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [31]:
import pandas as pd
data=pd.read_csv('../data/College.csv')
data

Unnamed: 0 Private   Apps  Accept  Enroll  Top10perc  \
0      Abilene Christian University     Yes   1660    1232     721         23   
1                Adelphi University     Yes   2186    1924     512         16   
2                    Adrian College     Yes   1428    1097     336         22   
3               Agnes Scott College     Yes    417     349     137         60   
4         Alaska Pacific University     Yes    193     146      55         16   
..                              ...     ...    ...     ...     ...        ...   
772         Worcester State College      No   2197    1515     543          4   
773               Xavier University     Yes   1959    1805     695         24   
774  Xavier University of Louisiana     Yes   2097    1915     695         34   
775                 Yale University     Yes  10705    2453    1317         95   
776    York College of Pennsylvania     Yes   2989    1855     691         28   

     Top25perc  F.Undergrad  P.Undergrad  Outstate  Room.Board  Books  \
0           52         2885          537      7440        3300    450   
1           29         2683         1227     12280        6450    750   
2           50         1036           99     11250        3750    400   
3           89          510           63     12960        5450    450   
4           44          249          869      7560        4120    800   
..         ...          ...          ...       ...         ...    ...   
772         26         3089         2029      6797        3900    500   
773         47         2849         1107     11520        4960    600   
774         61         2793          166      6900        4200    617   
775         99         5217           83     19840        6510    630   
776         63         2988         1726      4990        3560    500   

     Personal  PhD  Terminal  S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0        2200   70        78       18.1           12    7041         60  
1        1500   29        30       12.2           16   10527         56  
2        1165   53        66       12.9           30    8735         54  
3         875   92        97        7.7           37   19016         59  
4        1500   76        72       11.9            2   10922         15  
..        ...  ...       ...        ...          ...     ...        ...  
772      1200   60        60       21.0           14    4469         40  
773      1250   73        75       13.3           31    9189         83  
774       781   67        75       14.4           20    8323         49  
775      2115   96        96        5.8           49   40386         99  
776      1250   75        75       18.1           28    4509         99  

[777 rows x 19 columns]

# 열 이름 바꾸기

In [32]:
data.rename(columns={'Unnamed: 0': 'univ_name'}, inplace=True)
data

univ_name Private   Apps  Accept  Enroll  Top10perc  \
0      Abilene Christian University     Yes   1660    1232     721         23   
1                Adelphi University     Yes   2186    1924     512         16   
2                    Adrian College     Yes   1428    1097     336         22   
3               Agnes Scott College     Yes    417     349     137         60   
4         Alaska Pacific University     Yes    193     146      55         16   
..                              ...     ...    ...     ...     ...        ...   
772         Worcester State College      No   2197    1515     543          4   
773               Xavier University     Yes   1959    1805     695         24   
774  Xavier University of Louisiana     Yes   2097    1915     695         34   
775                 Yale University     Yes  10705    2453    1317         95   
776    York College of Pennsylvania     Yes   2989    1855     691         28   

     Top25perc  F.Undergrad  P.Undergrad  Outstate  Room.Board  Books  \
0           52         2885          537      7440        3300    450   
1           29         2683         1227     12280        6450    750   
2           50         1036           99     11250        3750    400   
3           89          510           63     12960        5450    450   
4           44          249          869      7560        4120    800   
..         ...          ...          ...       ...         ...    ...   
772         26         3089         2029      6797        3900    500   
773         47         2849         1107     11520        4960    600   
774         61         2793          166      6900        4200    617   
775         99         5217           83     19840        6510    630   
776         63         2988         1726      4990        3560    500   

     Personal  PhD  Terminal  S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0        2200   70        78       18.1           12    7041         60  
1        1500   29        30       12.2           16   10527         56  
2        1165   53        66       12.9           30    8735         54  
3         875   92        97        7.7           37   19016         59  
4        1500   76        72       11.9            2   10922         15  
..        ...  ...       ...        ...          ...     ...        ...  
772      1200   60        60       21.0           14    4469         40  
773      1250   73        75       13.3           31    9189         83  
774       781   67        75       14.4           20    8323         49  
775      2115   96        96        5.8           49   40386         99  
776      1250   75        75       18.1           28    4509         99  

[777 rows x 19 columns]

# Yes -> 1로 No-> 0으로 변환

In [33]:
data['Private']=data['Private'].map({'Yes':1,'No':0})
data['Private']

0      1
1      1
2      1
3      1
4      1
      ..
772    0
773    1
774    1
775    1
776    1
Name: Private, Length: 777, dtype: int64

In [34]:
y=data['Private']
y

0      1
1      1
2      1
3      1
4      1
      ..
772    0
773    1
774    1
775    1
776    1
Name: Private, Length: 777, dtype: int64

# 대학 이름 숫자로 변환

In [35]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit(data['univ_name'])

LabelEncoder()

In [36]:
le.transform(data['univ_name'])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  30,  29,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  52,
        51,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 139, 137, 138, 140, 141, 143,
       142, 144, 145, 146, 148, 147, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 161, 162, 163, 160, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [37]:
data['univ_name']=le.transform(data['univ_name'])

In [38]:
data['univ_name']

0        0
1        1
2        2
3        3
4        4
      ... 
772    772
773    773
774    774
775    775
776    776
Name: univ_name, Length: 777, dtype: int32

In [39]:
#from sklearn.feature_extraction.text import TfidfVectorizer
#from sklearn.decomposition import TruncatedSVD

In [40]:
#tfidf_vec = TfidfVectorizer(max_features=15, token_pattern="\w+")
#svd = TruncatedSVD(n_components=10)
#tfidf_array = svd.fit_transform(tfidf_vec.fit_transform(data["univ_name"]))
#for i in range(tfidf_array.shape[1]):
#    data.insert(len(data.columns), column = 'name_' + str(i), value = tfidf_array [:,i])
#data

# 0번째 컬럼 인덱스 만들기

In [41]:
data.set_index('univ_name',inplace=True)
data.columns

Index(['Private', 'Apps', 'Accept', 'Enroll', 'Top10perc', 'Top25perc',
       'F.Undergrad', 'P.Undergrad', 'Outstate', 'Room.Board', 'Books',
       'Personal', 'PhD', 'Terminal', 'S.F.Ratio', 'perc.alumni', 'Expend',
       'Grad.Rate'],
      dtype='object')

In [42]:
X=data.loc[:,:]
del X['Private']
X

Apps  Accept  Enroll  Top10perc  Top25perc  F.Undergrad  \
univ_name                                                             
0           1660    1232     721         23         52         2885   
1           2186    1924     512         16         29         2683   
2           1428    1097     336         22         50         1036   
3            417     349     137         60         89          510   
4            193     146      55         16         44          249   
...          ...     ...     ...        ...        ...          ...   
772         2197    1515     543          4         26         3089   
773         1959    1805     695         24         47         2849   
774         2097    1915     695         34         61         2793   
775        10705    2453    1317         95         99         5217   
776         2989    1855     691         28         63         2988   

           P.Undergrad  Outstate  Room.Board  Books  Personal  PhD  Terminal  \
univ_name                                                                      
0                  537      7440        3300    450      2200   70        78   
1                 1227     12280        6450    750      1500   29        30   
2                   99     11250        3750    400      1165   53        66   
3                   63     12960        5450    450       875   92        97   
4                  869      7560        4120    800      1500   76        72   
...                ...       ...         ...    ...       ...  ...       ...   
772               2029      6797        3900    500      1200   60        60   
773               1107     11520        4960    600      1250   73        75   
774                166      6900        4200    617       781   67        75   
775                 83     19840        6510    630      2115   96        96   
776               1726      4990        3560    500      1250   75        75   

           S.F.Ratio  perc.alumni  Expend  Grad.Rate  
univ_name                                             
0               18.1           12    7041         60  
1               12.2           16   10527         56  
2               12.9           30    8735         54  
3                7.7           37   19016         59  
4               11.9            2   10922         15  
...              ...          ...     ...        ...  
772             21.0           14    4469         40  
773             13.3           31    9189         83  
774             14.4           20    8323         49  
775              5.8           49   40386         99  
776             18.1           28    4509         99  

[777 rows x 17 columns]

In [43]:
X.shape

(777, 17)

# X값 표준화(StandardScaler)

In [44]:
from sklearn.preprocessing import StandardScaler

In [45]:
scaler = StandardScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)
np.mean(X_scaled), np.std(X_scaled)

(2.0441081049953674e-17, 0.9999999999999999)

# X_scaled, y 값 리스트로 만들기 tolist()

In [46]:
x=X_scaled.tolist()
x

[[-0.34688181931102013,
  -0.32120545330977984,
  -0.06350890112710722,
  -0.2585828007174153,
  -0.19182741580158905,
  -0.16811578105948569,
  -0.20920713118295584,
  -0.7463558876654935,
  -0.9649047311227198,
  -0.602312158738608,
  1.2700451531967583,
  -0.16302792483541048,
  -0.11572870260631442,
  1.013775944192749,
  -0.8675741886081831,
  -0.5019100843535785,
  -0.3182519406494316],
 [-0.21088403973145867,
  -0.03870299078454346,
  -0.2885842138750081,
  -0.6556555994475174,
  -1.3539113981033501,
  -0.20978847963226877,
  0.24430704587297267,
  0.4574963888004467,
  1.9092078682257194,
  1.215879791454602,
  0.2355149245178388,
  -2.675645535615127,
  -3.378175937984309,
  -0.4777044989917245,
  -0.5445722027200383,
  0.16610985008782322,
  -0.5512618420719132],
 [-0.40686563083660615,
  -0.3763179279353679,
  -0.47812131934692464,
  -0.315307486250287,
  -0.2928781968713074,
  -0.5495653833420399,
  -0.49709004357498005,
  0.20130468533765358,
  -0.5543172169300856,
  -0.90

In [47]:
len(x[0])

17

In [48]:
y1=list()
for i in y.tolist():
    y1.append([i])
y=y1
y

[[1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [0],
 [1],
 [0],
 [1],
 [0],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [0],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [0],
 [1]

# 텐서플로우 구현

In [49]:
import numpy as np
import tensorflow as tf
X_h = tf.placeholder(dtype=tf.float32, 
                     shape=[777,17])

W = tf.Variable(tf.random_normal([17,1]))

B = tf.Variable(tf.random_normal([1]))

In [50]:
temp = tf.matmul(X_h, W)
temp

<tf.Tensor 'MatMul_1:0' shape=(777, 1) dtype=float32>

In [51]:
# y_pred = wx + b
y_pred = tf.add(temp, B)
y_pred

<tf.Tensor 'Add_3:0' shape=(777, 1) dtype=float32>

In [52]:
loss = tf.reduce_mean(tf.square(y_pred-y))
loss

<tf.Tensor 'Mean:0' shape=() dtype=float32>

In [53]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1)
optimizer

In [54]:
train_op = optimizer.minimize(loss)
train_op

<tf.Operation 'GradientDescent' type=NoOp>

In [55]:
init_op = tf.global_variables_initializer()

In [59]:
with tf.Session() as sess:
    sess.run(init_op)
    for i in range(200):
        sess.run([temp, y_pred, loss, train_op], feed_dict={X_h:x})
        print(sess.run(loss, feed_dict={X_h:x}))
    print(sess.run([W, B]))

4.88187
3.7640135
3.174611
2.7191968
2.3573627
2.0640342
1.8219651
1.6191031
1.4468842
1.2991072
1.1711938
1.0596883
0.9619296
0.8758244
0.7996957
0.73217547
0.67213094
0.6186129
0.570816
0.528052
0.48972782
0.4553297
0.42440996
0.3965778
0.3714906
0.3488469
0.32838133
0.3098598
0.2930754
0.27784503
0.2640063
0.2514152
0.23994397
0.22947879
0.21991852
0.21117306
0.20316195
0.19581361
0.1890638
0.18285534
0.17713693
0.17186257
0.16699119
0.1624857
0.15831304
0.1544432
0.15084942
0.14750741
0.14439535
0.14149357
0.13878426
0.13625126
0.13387999
0.13165729
0.12957114
0.12761065
0.12576595
0.124028005
0.122388676
0.120840415
0.11937649
0.11799058
0.11667707
0.11543074
0.11424682
0.11312091
0.11204902
0.11102745
0.11005283
0.109122045
0.1082322
0.107380666
0.10656503
0.10578295
0.10503246
0.10431151
0.10361843
0.102951534
0.10230928
0.10169022
0.10109307
0.10051662
0.0999597
0.09942123
0.09890028
0.0983959
0.097907245
0.09743346
0.096973896
0.096527755
0.09609444
0.09567331
0.09526384
0.094

# Components of Neural Networks (cont.)
### ▪A set of weights and biases between each layer, W and b 
### 레이어사이에 가중치와 바이어스가 있음
### ▪A choice of activation function for each hidden layer, σ 
### 각 히든레이어에 엑티베이션 함수가 있음

# Output Calculations
### Receive a set of inputs, perform progressively complex calculations on them, and give output to solve real world problems like classification

### 입력을 받아 계산한후 출력을 함. 분류문제에 적합

In [57]:
# pip install tensorflow-datasets
import tensorflow_datasets as tfds
tfds.list_builders()

['abstract_reasoning',
 'aeslc',
 'aflw2k3d',
 'amazon_us_reviews',
 'bair_robot_pushing_small',
 'big_patent',
 'bigearthnet',
 'billsum',
 'binarized_mnist',
 'binary_alpha_digits',
 'c4',
 'caltech101',
 'caltech_birds2010',
 'caltech_birds2011',
 'cars196',
 'cassava',
 'cats_vs_dogs',
 'celeb_a',
 'celeb_a_hq',
 'chexpert',
 'cifar10',
 'cifar100',
 'cifar10_1',
 'cifar10_corrupted',
 'citrus_leaves',
 'clevr',
 'cmaterdb',
 'cnn_dailymail',
 'coco',
 'coil100',
 'colorectal_histology',
 'colorectal_histology_large',
 'curated_breast_imaging_ddsm',
 'cycle_gan',
 'deep_weeds',
 'definite_pronoun_resolution',
 'diabetic_retinopathy_detection',
 'dmlab',
 'downsampled_imagenet',
 'dsprites',
 'dtd',
 'duke_ultrasound',
 'dummy_dataset_shared_generator',
 'dummy_mnist',
 'emnist',
 'esnli',
 'eurosat',
 'fashion_mnist',
 'flores',
 'food101',
 'gap',
 'gigaword',
 'glue',
 'groove',
 'higgs',
 'horses_or_humans',
 'i_naturalist2017',
 'image_label_folder',
 'imagenet2012',
 'imagenet